# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SZCollectionViewManagerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  platform :ios, '8.0'
   pod 'SZCollectionViewManager', :path => '../'
   pod 'SZTableViewManager'
  
  # Pods for SZCollectionViewManagerExample
  
  pod 'SnapKit'
  pod 'Kingfisher'

  target 'SZCollectionViewManagerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SZCollectionViewManagerExampleUITests' do
    # Pods for testing
  end

end
